#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "build-essential"
cookbook "database",
  :git => "https://github.com/opscode-cookbooks/database.git"
cookbook "django-application",
  :git => "https://github.com/blackrobot/chef-django-application.git"
cookbook "dotfiles",
  :git => "https://github.com/blackrobot/chef-dotfiles.git"
cookbook "git"
cookbook "memcached"
cookbook "mysql"
cookbook "nginx"
cookbook "ntp"
cookbook "python"
cookbook "sudo"
cookbook "uwsgi",
  :git => "https://github.com/blackrobot/chef-uwsgi.git"
cookbook "user",
  :git => "https://github.com/fnichol/chef-user.git"
cookbook "vim"
