#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "build-essential"
cookbook "database",
  :git => "https://github.com/opscode-cookbooks/database.git"
cookbook "git"
cookbook "memcached"
cookbook "postgresql"
cookbook "nginx"
cookbook "ntp"
cookbook "python"
cookbook "sudo"
cookbook "supervisor"
cookbook "user",
  :git => "https://github.com/fnichol/chef-user.git"
cookbook "vim"

cookbook "django-app",
  :git => "https://github.com/blackrobot/chef-django-app.git"
cookbook "git-ssh-wrapper",
  :git => "https://github.com/blackrobot/chef-git-ssh-wrapper.git"
cookbook "dotfiles",
  :git => "https://github.com/blackrobot/chef-dotfiles.git"
cookbook "uwsgi",
  :git => "https://github.com/blackrobot/chef-uwsgi.git"
cookbook "virtualenvwrapper",
  :git => "https://github.com/blackrobot/chef-virtualenvwrapper.git"
